vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pictures:
            uri_prefix: /picture/file
            upload_destination: '%kernel.project_dir%/public/pictures/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer